# Generated by Django 3.2.6 on 2021-08-04 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='highest_race_finish',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='driver',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
