# Generated by Django 2.2.5 on 2021-07-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_app', '0002_pilot'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='points',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
