# Generated by Django 2.2.5 on 2021-07-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_app', '0003_pilot_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
