# Generated by Django 2.2.5 on 2021-07-21 09:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f1_app', '0005_auto_20210720_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('capacity', models.DecimalField(decimal_places=3, max_digits=6)),
                ('gps_held', models.PositiveIntegerField()),
                ('length', models.DecimalField(decimal_places=3, max_digits=4)),
                ('lap_record', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('sold_out', models.BooleanField()),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1_app.Circuit')),
                ('first_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_place', to='f1_app.Pilot')),
                ('second_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_place', to='f1_app.Pilot')),
                ('third_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_place', to='f1_app.Pilot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
