# Generated by Django 2.2.5 on 2021-07-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('capacity', models.DecimalField(decimal_places=3, max_digits=6)),
                ('gps_held', models.PositiveIntegerField()),
                ('length', models.DecimalField(decimal_places=3, max_digits=4)),
                ('lap_record', models.CharField(max_length=30)),
            ],
        ),
    ]
