# Generated by Django 2.2.5 on 2021-07-28 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('circuits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('sold_out', models.BooleanField()),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circuits.Circuit')),
                ('first_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_place', to='drivers.Driver')),
                ('second_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_place', to='drivers.Driver')),
                ('third_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_place', to='drivers.Driver')),
            ],
        ),
    ]
