# Generated by Django 3.2.6 on 2021-08-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='weather',
            field=models.CharField(default='Data not available', max_length=50),
        ),
    ]
