# Generated by Django 3.2.6 on 2021-08-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('power_unit', models.CharField(max_length=30)),
                ('world_championships', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=30)),
            ],
        ),
    ]
